//@url = http://localhost:4000
@url = https://golfcourseproject-courseservice.azurewebsites.net
@apiKey = 0780d1ad8

### Get Course by ID
GET {{url}}/api/course/0038f6eb-e419-40f5-bc90-b1145a533239 HTTP/1.1
content-type: application/json
X-ApiKey: {{apiKey}}
###

### Create Course
POST {{url}}/api/course/create HTTP/1.1
content-type: application/json
X-ApiKey: {{apiKey}}

{    
    "facilityId": "2bbe4135-5852-4d49-9893-0dbfdd7f2539",
    "name": "Fields Ranch West",
    "description": "",
    "longitude": -96.85203550989914,
    "latitude": 33.21346909607158,
    "address1": "3725 PGA Pkwy",
    "city": "Frisco",
    "state": "TX",
    "postalCode": 75033,
    "YearOpened": 2023,
    "Designer": "Beau Welling"
}

###

### Create Facility
POST {{url}}/api/facility/create HTTP/1.1
content-type: application/json
X-ApiKey: {{apiKey}}

{
    "name": "Cabot Citrus Farms",
    "description": "A beautiful golf course located in the heart of Florida.",
    "address1": "7590 Ponce De Leon Blvd",
    "city": "Brooksville",
    "state": "FL",   
    "Type": 1,
    "postalCode": 34614,
    "longitude": -82.4799264411736,
    "latitude": 28.68349223484484,
    "phone": "(352) 796-4653",
    "website": "http://www.cabotcitrusfarms.com",
    "email": "reservations@cabotcitrusfarms.com",
    "facebook": "https://www.facebook.com/cabotcitrusfarms",
    "instagram": "https://www.instagram.com/cabotcitrusfarms"
}

### List By Ids
POST {{url}}/api/course/list HTTP/1.1
content-type: application/json
X-ApiKey: {{apiKey}}

{
    "ids": [
      "dc12b631-341b-4d6e-85f1-f24cdc14a322",
      "a14c616f-7e85-4371-9840-e0ccbedc775e",
      "1392ca84-0f1a-487b-9ada-141ffd7b93b4",
      "e5bb6246-c6be-42ff-b9e2-118c88cd122e"
    ]
  }

### Search
POST {{url}}/api/course/search/ai HTTP/1.1
content-type: application/json
X-ApiKey: {{apiKey}}

{
    "state": "FL"
}