name: Send pull request to azure boards work item

on:
  pull_request_target:
    types: [opened, edited, closed]
    branches:
      - main

jobs:
  alert:
    runs-on: ubuntu-latest  
    steps:       
    - uses: danhellem/github-actions-pr-to-work-item@master
      env:     
        ado_token: '${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}'
        github_token: '${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}'
        ado_organization: '${{ secrets.ADO_ORGANIZATION }}'
        ado_project: '${{ secrets.ADO_PROJECT }}'
        ado_wit: 'GitHub Pull Request' 
        ado_new_state: 'New'
        ado_close_state: 'Closed'
        ado_active_state: 'Active' 
